eth:
  url: https://sepolia.infura.io/v3/8c74af6f0b934262ac0c69351593a9ee
  wsUrl: wss://mainnet.infura.io/ws/v3/8c74af6f0b934262ac0c69351593a9ee
  chainId: 11155111

eth-wallet:
  mnemonics:
    - amused
    - multiply
    - ridge
    - ugly
    - volume
    - leisure
    - surge
    - fun
    - pony
    - clutch
    - surprise
    - whisper
#  "amused multiply ridge ugly volume leisure surge fun pony clutch surprise whisper"
  masterXPUB: "xpub6Dr94hHJ9cGuNXHeT76bL2gjab4w1brFnKrvbK5hH8XQV7vNAkFJU2EUv4vXyijbR7NszhZXD1PzxZ8Y4QTqrMxaeyAabwuhVCiHGaDUm3j"

